### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by squi-ddy** [appventure-nush/nush-link#28]
**Feature Improvements**
1. Allow teachers to add students
2. Let teachers see students' links
3. Point QR code to nush.link directly
4. See QR code after generation
5. Link click metrics
6. A/B redirects

**Todo**
Backend:
- [ ] Add functionality to delete authorised students (1)
- [ ] API to see student links (2)
- [ ] Track click stats (5)
- [ ] A/B support (6)

Frontend:
- [ ] Add/modify students UI (1)
- [ ] Improve links page to see students + add filtering (2)
- [ ] Modify QR code generation (3)
- [ ] Add functionality to see QR code (4)
- [ ] Add metrics view (5)
- [ ] Add A/B UI (6)
